@startuml demo

set namespaceSeparator ::

namespace ui {
	class SceneMenu {
		;
	}
	class SceneVisualizer {
		- ui::Controller controller;
		- visual::VisualDataStructure visualDS;
		- ui::Monitor monitor;
	}
	class Controller {
		- visual::VisualDataStructure visualDS;
	}
	class MethodTrigger {
		;
	}
	class Monitor {
		;
	}
}

namespace visual {

	abstract class VisualizedDataStructure {
		- ui::Monitor monitor;
	}
	class VisualizedStack {
		;
	}
	
	class VisualArray {
		;
	}
	class VisualArrayIndex {
		;
	}
	class VisualArrayNode {
		;
	}

	VisualizedDataStructure --|> VisualizedStack
}

class Main {
	;
}

class Director {
	;
}

Main o-- ui::SceneMenu
Main o-- ui::SceneVisualizer

ui::SceneVisualizer *- ui::Controller
ui::SceneVisualizer *-- visual::VisualizedDataStructure
ui::SceneVisualizer *-- ui::Monitor
ui::Controller -down-> visual::VisualizedDataStructure
visual::VisualizedDataStructure -up-> ui::Monitor

@enduml